//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymTECRelational.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        public int Id { get; set; }
        public Nullable<System.TimeSpan> Hora_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tipo_Servicio { get; set; }
        public System.TimeSpan Hora_Final { get; set; }
        public string Sucursal { get; set; }
        public string Instructor { get; set; }
        public string Modalidad { get; set; }
        public int Capacidad { get; set; }
    
        public virtual Cliente_Clase Cliente_Clase { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Sucursal Sucursal1 { get; set; }
        public virtual Tipo_Servicio Tipo_Servicio1 { get; set; }
    }
}
