//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymTECRelational.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clase()
        {
            this.Cliente_Clase = new HashSet<Cliente_Clase>();
        }
    
        public int Id { get; set; }
        public System.TimeSpan Hora_Inicio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo_Servicio { get; set; }
        public System.TimeSpan Hora_Final { get; set; }
        public string Sucursal { get; set; }
        public string Instructor { get; set; }
        public string Modalidad { get; set; }
        public int Capacidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente_Clase> Cliente_Clase { get; set; }
    }
}
