//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymTECRelational.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Clases = new HashSet<Clase>();
            this.Sucursals = new HashSet<Sucursal>();
        }
    
        public string Cedula { get; set; }
        public string Puesto { get; set; }
        public string Planilla { get; set; }
        public string Distrito { get; set; }
        public string Canton { get; set; }
        public string Provincia { get; set; }
        public string Sucursal { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public decimal Salario { get; set; }
        public string Email { get; set; }
        public string Contraseña { get; set; }
        public string Salt { get; set; }
        public string Token { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clase> Clases { get; set; }
        public virtual Direccion Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sucursal> Sucursals { get; set; }
        public virtual Planilla Planilla1 { get; set; }
        public virtual Puesto Puesto1 { get; set; }
        public virtual Sucursal Sucursal1 { get; set; }
    }
}
