//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymTECRelational.EntityFramework
{
    using System;
    
    public partial class getEmployeeByMail_Result1
    {
        public string Cedula { get; set; }
        public string Puesto { get; set; }
        public string Planilla { get; set; }
        public string Distrito { get; set; }
        public string Canton { get; set; }
        public string Provincia { get; set; }
        public string Sucursal { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public decimal Salario { get; set; }
        public string Email { get; set; }
        public string Contraseña { get; set; }
        public string Salt { get; set; }
        public string Token { get; set; }
    }
}
