//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymTECRelational.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GymTECEntities : DbContext
    {
        public GymTECEntities()
            : base("name=GymTECEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clase> Clases { get; set; }
        public virtual DbSet<Cliente_Clase> Cliente_Clase { get; set; }
        public virtual DbSet<Direccion> Direccions { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Maquina> Maquinas { get; set; }
        public virtual DbSet<Planilla> Planillas { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Puesto> Puestoes { get; set; }
        public virtual DbSet<Sucursal> Sucursals { get; set; }
        public virtual DbSet<Tipo_Equipo> Tipo_Equipo { get; set; }
        public virtual DbSet<Tipo_Servicio> Tipo_Servicio { get; set; }
        public virtual DbSet<Tratamiento_Spa> Tratamiento_Spa { get; set; }
        public virtual DbSet<Sucursal_Telefono> Sucursal_Telefono { get; set; }
    
        public virtual ObjectResult<Empleado> selectAllAdmins()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empleado>("selectAllAdmins");
        }
    
        public virtual ObjectResult<Empleado> selectAllAdmins(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empleado>("selectAllAdmins", mergeOption);
        }
    
        public virtual ObjectResult<Nullable<bool>> insertEmployee(string cedula, string puesto, string planilla, string distrito, string canton, string provincia, string sucursal, string nombre, string apellidos, Nullable<decimal> salario, string email, string contraseña, string salt, string token)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var puestoParameter = puesto != null ?
                new ObjectParameter("Puesto", puesto) :
                new ObjectParameter("Puesto", typeof(string));
    
            var planillaParameter = planilla != null ?
                new ObjectParameter("Planilla", planilla) :
                new ObjectParameter("Planilla", typeof(string));
    
            var distritoParameter = distrito != null ?
                new ObjectParameter("Distrito", distrito) :
                new ObjectParameter("Distrito", typeof(string));
    
            var cantonParameter = canton != null ?
                new ObjectParameter("Canton", canton) :
                new ObjectParameter("Canton", typeof(string));
    
            var provinciaParameter = provincia != null ?
                new ObjectParameter("Provincia", provincia) :
                new ObjectParameter("Provincia", typeof(string));
    
            var sucursalParameter = sucursal != null ?
                new ObjectParameter("Sucursal", sucursal) :
                new ObjectParameter("Sucursal", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var salarioParameter = salario.HasValue ?
                new ObjectParameter("Salario", salario) :
                new ObjectParameter("Salario", typeof(decimal));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            var saltParameter = salt != null ?
                new ObjectParameter("Salt", salt) :
                new ObjectParameter("Salt", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("insertEmployee", cedulaParameter, puestoParameter, planillaParameter, distritoParameter, cantonParameter, provinciaParameter, sucursalParameter, nombreParameter, apellidosParameter, salarioParameter, emailParameter, contraseñaParameter, saltParameter, tokenParameter);
        }
    
        public virtual ObjectResult<Empleado> getEmployeeById(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empleado>("getEmployeeById", cedulaParameter);
        }
    
        public virtual ObjectResult<Empleado> getEmployeeById(string cedula, MergeOption mergeOption)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empleado>("getEmployeeById", mergeOption, cedulaParameter);
        }
    
        public virtual ObjectResult<Empleado> getEmployeeByMail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empleado>("getEmployeeByMail", emailParameter);
        }
    
        public virtual ObjectResult<Empleado> getEmployeeByMail(string email, MergeOption mergeOption)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Empleado>("getEmployeeByMail", mergeOption, emailParameter);
        }
    
        public virtual int assignTokenAdmin(string token, Nullable<int> id)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("assignTokenAdmin", tokenParameter, idParameter);
        }
    
        public virtual int assignTokenEmployee(string token, string id)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("assignTokenEmployee", tokenParameter, idParameter);
        }
    
        public virtual int getAdminByMail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getAdminByMail", emailParameter);
        }
    
        public virtual int insertAdmin(string email, string nombre, string apellidos, string contraseña, string salt, string token)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("Contraseña", contraseña) :
                new ObjectParameter("Contraseña", typeof(string));
    
            var saltParameter = salt != null ?
                new ObjectParameter("Salt", salt) :
                new ObjectParameter("Salt", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertAdmin", emailParameter, nombreParameter, apellidosParameter, contraseñaParameter, saltParameter, tokenParameter);
        }
    
        public virtual int insertGym(string nombre, string distrito, string canton, string provincia, Nullable<System.DateTime> fecha_Apertura, Nullable<int> capacidad_Max, string gerente)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var distritoParameter = distrito != null ?
                new ObjectParameter("Distrito", distrito) :
                new ObjectParameter("Distrito", typeof(string));
    
            var cantonParameter = canton != null ?
                new ObjectParameter("Canton", canton) :
                new ObjectParameter("Canton", typeof(string));
    
            var provinciaParameter = provincia != null ?
                new ObjectParameter("Provincia", provincia) :
                new ObjectParameter("Provincia", typeof(string));
    
            var fecha_AperturaParameter = fecha_Apertura.HasValue ?
                new ObjectParameter("Fecha_Apertura", fecha_Apertura) :
                new ObjectParameter("Fecha_Apertura", typeof(System.DateTime));
    
            var capacidad_MaxParameter = capacidad_Max.HasValue ?
                new ObjectParameter("Capacidad_Max", capacidad_Max) :
                new ObjectParameter("Capacidad_Max", typeof(int));
    
            var gerenteParameter = gerente != null ?
                new ObjectParameter("Gerente", gerente) :
                new ObjectParameter("Gerente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertGym", nombreParameter, distritoParameter, cantonParameter, provinciaParameter, fecha_AperturaParameter, capacidad_MaxParameter, gerenteParameter);
        }
    
        public virtual ObjectResult<Sucursal> selectAllGyms()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sucursal>("selectAllGyms");
        }
    
        public virtual ObjectResult<Sucursal> selectAllGyms(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sucursal>("selectAllGyms", mergeOption);
        }
    
        public virtual int activateGymSpa(Nullable<bool> state, string nombre)
        {
            var stateParameter = state.HasValue ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(bool));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("activateGymSpa", stateParameter, nombreParameter);
        }
    
        public virtual int activateGymStore(Nullable<bool> state, string nombre)
        {
            var stateParameter = state.HasValue ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(bool));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("activateGymStore", stateParameter, nombreParameter);
        }
    
        public virtual ObjectResult<Sucursal> selectGym(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sucursal>("selectGym", nombreParameter);
        }
    
        public virtual ObjectResult<Sucursal> selectGym(string nombre, MergeOption mergeOption)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sucursal>("selectGym", mergeOption, nombreParameter);
        }
    
        public virtual int updateGym(string currentname, string nombre, string distrito, string canton, string provincia, Nullable<System.DateTime> fecha_Apertura, Nullable<int> capacidad_Max, string gerente)
        {
            var currentnameParameter = currentname != null ?
                new ObjectParameter("Currentname", currentname) :
                new ObjectParameter("Currentname", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var distritoParameter = distrito != null ?
                new ObjectParameter("Distrito", distrito) :
                new ObjectParameter("Distrito", typeof(string));
    
            var cantonParameter = canton != null ?
                new ObjectParameter("Canton", canton) :
                new ObjectParameter("Canton", typeof(string));
    
            var provinciaParameter = provincia != null ?
                new ObjectParameter("Provincia", provincia) :
                new ObjectParameter("Provincia", typeof(string));
    
            var fecha_AperturaParameter = fecha_Apertura.HasValue ?
                new ObjectParameter("Fecha_Apertura", fecha_Apertura) :
                new ObjectParameter("Fecha_Apertura", typeof(System.DateTime));
    
            var capacidad_MaxParameter = capacidad_Max.HasValue ?
                new ObjectParameter("Capacidad_Max", capacidad_Max) :
                new ObjectParameter("Capacidad_Max", typeof(int));
    
            var gerenteParameter = gerente != null ?
                new ObjectParameter("Gerente", gerente) :
                new ObjectParameter("Gerente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateGym", currentnameParameter, nombreParameter, distritoParameter, cantonParameter, provinciaParameter, fecha_AperturaParameter, capacidad_MaxParameter, gerenteParameter);
        }
    
        public virtual int deleteGym(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteGym", nombreParameter);
        }
    
        public virtual int addPhoneNumb(string nombre, string telefono)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addPhoneNumb", nombreParameter, telefonoParameter);
        }
    
        public virtual int deletePhoneNumb(string telefono)
        {
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletePhoneNumb", telefonoParameter);
        }
    
        public virtual ObjectResult<Sucursal_Telefono> getAllPhoneNumbByGym(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sucursal_Telefono>("getAllPhoneNumbByGym", nombreParameter);
        }
    
        public virtual ObjectResult<Sucursal_Telefono> getAllPhoneNumbByGym(string nombre, MergeOption mergeOption)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sucursal_Telefono>("getAllPhoneNumbByGym", mergeOption, nombreParameter);
        }
    
        public virtual int updatePhoneNumb(string currentNumb, string nombre, string telefono)
        {
            var currentNumbParameter = currentNumb != null ?
                new ObjectParameter("CurrentNumb", currentNumb) :
                new ObjectParameter("CurrentNumb", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatePhoneNumb", currentNumbParameter, nombreParameter, telefonoParameter);
        }
    
        public virtual int deleteMachine(string serial)
        {
            var serialParameter = serial != null ?
                new ObjectParameter("Serial", serial) :
                new ObjectParameter("Serial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteMachine", serialParameter);
        }
    
        public virtual ObjectResult<Maquina> getAllMachines()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Maquina>("getAllMachines");
        }
    
        public virtual ObjectResult<Maquina> getAllMachines(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Maquina>("getAllMachines", mergeOption);
        }
    
        public virtual ObjectResult<Maquina> getMachine(string serial)
        {
            var serialParameter = serial != null ?
                new ObjectParameter("Serial", serial) :
                new ObjectParameter("Serial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Maquina>("getMachine", serialParameter);
        }
    
        public virtual ObjectResult<Maquina> getMachine(string serial, MergeOption mergeOption)
        {
            var serialParameter = serial != null ?
                new ObjectParameter("Serial", serial) :
                new ObjectParameter("Serial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Maquina>("getMachine", mergeOption, serialParameter);
        }
    
        public virtual ObjectResult<Maquina> getMachinesByGym(string sucursal)
        {
            var sucursalParameter = sucursal != null ?
                new ObjectParameter("Sucursal", sucursal) :
                new ObjectParameter("Sucursal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Maquina>("getMachinesByGym", sucursalParameter);
        }
    
        public virtual ObjectResult<Maquina> getMachinesByGym(string sucursal, MergeOption mergeOption)
        {
            var sucursalParameter = sucursal != null ?
                new ObjectParameter("Sucursal", sucursal) :
                new ObjectParameter("Sucursal", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Maquina>("getMachinesByGym", mergeOption, sucursalParameter);
        }
    
        public virtual int insertMachine(string serial, string tipo_Equipo, string sucursal, string marca, Nullable<decimal> costo)
        {
            var serialParameter = serial != null ?
                new ObjectParameter("Serial", serial) :
                new ObjectParameter("Serial", typeof(string));
    
            var tipo_EquipoParameter = tipo_Equipo != null ?
                new ObjectParameter("Tipo_Equipo", tipo_Equipo) :
                new ObjectParameter("Tipo_Equipo", typeof(string));
    
            var sucursalParameter = sucursal != null ?
                new ObjectParameter("Sucursal", sucursal) :
                new ObjectParameter("Sucursal", typeof(string));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var costoParameter = costo.HasValue ?
                new ObjectParameter("Costo", costo) :
                new ObjectParameter("Costo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertMachine", serialParameter, tipo_EquipoParameter, sucursalParameter, marcaParameter, costoParameter);
        }
    
        public virtual int updateMachine(string currentSerial, string serial, string tipo_Equipo, string sucursal, string marca, Nullable<decimal> costo)
        {
            var currentSerialParameter = currentSerial != null ?
                new ObjectParameter("CurrentSerial", currentSerial) :
                new ObjectParameter("CurrentSerial", typeof(string));
    
            var serialParameter = serial != null ?
                new ObjectParameter("Serial", serial) :
                new ObjectParameter("Serial", typeof(string));
    
            var tipo_EquipoParameter = tipo_Equipo != null ?
                new ObjectParameter("Tipo_Equipo", tipo_Equipo) :
                new ObjectParameter("Tipo_Equipo", typeof(string));
    
            var sucursalParameter = sucursal != null ?
                new ObjectParameter("Sucursal", sucursal) :
                new ObjectParameter("Sucursal", typeof(string));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("Marca", marca) :
                new ObjectParameter("Marca", typeof(string));
    
            var costoParameter = costo.HasValue ?
                new ObjectParameter("Costo", costo) :
                new ObjectParameter("Costo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateMachine", currentSerialParameter, serialParameter, tipo_EquipoParameter, sucursalParameter, marcaParameter, costoParameter);
        }
    
        public virtual int deleteMachineType(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteMachineType", nombreParameter);
        }
    
        public virtual ObjectResult<Tipo_Equipo> getAllMachineTypes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tipo_Equipo>("getAllMachineTypes");
        }
    
        public virtual ObjectResult<Tipo_Equipo> getAllMachineTypes(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tipo_Equipo>("getAllMachineTypes", mergeOption);
        }
    
        public virtual ObjectResult<Tipo_Equipo> getMachineType(string typeName)
        {
            var typeNameParameter = typeName != null ?
                new ObjectParameter("TypeName", typeName) :
                new ObjectParameter("TypeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tipo_Equipo>("getMachineType", typeNameParameter);
        }
    
        public virtual ObjectResult<Tipo_Equipo> getMachineType(string typeName, MergeOption mergeOption)
        {
            var typeNameParameter = typeName != null ?
                new ObjectParameter("TypeName", typeName) :
                new ObjectParameter("TypeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tipo_Equipo>("getMachineType", mergeOption, typeNameParameter);
        }
    
        public virtual int insertMachineType(string nombre, string descripcion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertMachineType", nombreParameter, descripcionParameter);
        }
    
        public virtual int updateMachineType(string currentTypeName, string nombre, string descripcion)
        {
            var currentTypeNameParameter = currentTypeName != null ?
                new ObjectParameter("CurrentTypeName", currentTypeName) :
                new ObjectParameter("CurrentTypeName", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateMachineType", currentTypeNameParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int deleteJob(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteJob", nombreParameter);
        }
    
        public virtual ObjectResult<Puesto> getJob(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Puesto>("getJob", nombreParameter);
        }
    
        public virtual ObjectResult<Puesto> getJob(string nombre, MergeOption mergeOption)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Puesto>("getJob", mergeOption, nombreParameter);
        }
    
        public virtual ObjectResult<Puesto> gettAllJobs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Puesto>("gettAllJobs");
        }
    
        public virtual ObjectResult<Puesto> gettAllJobs(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Puesto>("gettAllJobs", mergeOption);
        }
    
        public virtual int insertJob(string nombre, string descripcion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertJob", nombreParameter, descripcionParameter);
        }
    
        public virtual int updateJob(string currentName, string nombre, string descripcion)
        {
            var currentNameParameter = currentName != null ?
                new ObjectParameter("CurrentName", currentName) :
                new ObjectParameter("CurrentName", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateJob", currentNameParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int deletePayroll(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletePayroll", nombreParameter);
        }
    
        public virtual ObjectResult<Planilla> getAllPayrolls()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Planilla>("getAllPayrolls");
        }
    
        public virtual ObjectResult<Planilla> getAllPayrolls(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Planilla>("getAllPayrolls", mergeOption);
        }
    
        public virtual ObjectResult<Planilla> getPayroll(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Planilla>("getPayroll", nombreParameter);
        }
    
        public virtual ObjectResult<Planilla> getPayroll(string nombre, MergeOption mergeOption)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Planilla>("getPayroll", mergeOption, nombreParameter);
        }
    
        public virtual int insertPayRoll(string nombre, string descripcion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertPayRoll", nombreParameter, descripcionParameter);
        }
    
        public virtual int updatePayRoll(string currentName, string nombre, string descripcion)
        {
            var currentNameParameter = currentName != null ?
                new ObjectParameter("CurrentName", currentName) :
                new ObjectParameter("CurrentName", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatePayRoll", currentNameParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int deleteTreatment(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteTreatment", idParameter);
        }
    
        public virtual ObjectResult<Tratamiento_Spa> getAllTreatments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tratamiento_Spa>("getAllTreatments");
        }
    
        public virtual ObjectResult<Tratamiento_Spa> getAllTreatments(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tratamiento_Spa>("getAllTreatments", mergeOption);
        }
    
        public virtual ObjectResult<Tratamiento_Spa> getTreatment(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tratamiento_Spa>("getTreatment", idParameter);
        }
    
        public virtual ObjectResult<Tratamiento_Spa> getTreatment(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tratamiento_Spa>("getTreatment", mergeOption, idParameter);
        }
    
        public virtual int insertTreatment(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertTreatment", nombreParameter);
        }
    
        public virtual int updateTreatment(Nullable<int> currentId, string nombre)
        {
            var currentIdParameter = currentId.HasValue ?
                new ObjectParameter("CurrentId", currentId) :
                new ObjectParameter("CurrentId", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateTreatment", currentIdParameter, nombreParameter);
        }
    }
}
