//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymTECRelational.EntityFramework
{
    using System;
    
    public partial class searchClasses_Result1
    {
        public int Id { get; set; }
        public System.TimeSpan Hora_Inicio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo_Servicio { get; set; }
        public System.TimeSpan Hora_Final { get; set; }
        public string Sucursal { get; set; }
        public string Instructor { get; set; }
        public string Modalidad { get; set; }
        public int Capacidad { get; set; }
    }
}
