//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymTECRelational.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public string Nombre { get; set; }
        public string Distrito { get; set; }
        public string Canton { get; set; }
        public string Provincia { get; set; }
        public System.DateTime Fecha_Apertura { get; set; }
        public int Capacidad_Max { get; set; }
        public string Gerente { get; set; }
        public Nullable<bool> Tienda_Act { get; set; }
        public Nullable<bool> Spa_Act { get; set; }
        public string imageURL { get; set; }
    }
}
